/**
 * Seed «Куда сходить в Сочи» — реальные места Сочи 2026.
 * Usage: node scripts/seed-places.mjs
 * Requires DATABASE_URL and prisma generate.
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const connectionString =
  process.env.DATABASE_URL ||
  'postgresql://sochi:sochi@127.0.0.1:5432/sochi_portal?schema=public';
const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString }),
});

function features(items) {
  return JSON.stringify(items);
}

const PLACES = [
  {
    id: 'place_olympic_park',
    slug: 'olimpiyskiy-park',
    title: 'Олимпийский парк',
    summary: 'Медаль-плаза, фонтаны и арены Игр-2014 у Чёрного моря.',
    description:
      'Сердце Имеретинской низменности: Олимпийский парк с Медаль-плазой, поющим фонтаном, ледовыми дворцами и променадом к морю. Вечером особенно красиво — огни арен и шоу фонтанов. Удобно совмещать с Имеретинским пляжем и Сочи-Парком.',
    category: 'UNIQUE',
    address: 'г. Сочи, Адлер, Олимпийский парк',
    district: 'Адлер / Имеретинская',
    lat: 43.4055,
    lng: 39.9555,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
    bestSeason: 'Круглый год, вечерние шоу — май–октябрь',
    visitTime: '2–4 часа',
    priceHint: 'Парк бесплатно; аттракции и музеи — по билетам',
    sortOrder: 10,
    featuresJson: features([
      { icon: 'sparkles', title: 'Шоу фонтанов', text: 'Вечерняя подсветка и музыка на Медаль-плазе' },
      { icon: 'bike', title: 'Велопрокат', text: 'Круговой маршрут вокруг арен' },
      { icon: 'camera', title: 'Фото-точки', text: 'Олимпийский огонь, кольца, панорама моря' },
    ]),
    tips: 'Приезжайте к закату: меньше жары и лучше свет. Парковка у арен платная в пик сезона.',
  },
  {
    id: 'place_rosa_khutor',
    slug: 'roza-khutor',
    title: 'Роза Хутор / Красная Поляна',
    summary: 'Горы, канатки и променад курортного посёлка.',
    description:
      'Курортный кластер Красной Поляны: Роза Хутор с набережной Мзымты, канатными дорогами и видами на хребты. Летом — трекинг и смотровые, зимой — лыжи и сноуборд. Рядом Газпром и Красная Поляна Resort.',
    category: 'MOUNTAIN',
    address: 'г. Сочи, Эсто-Садок, Роза Хутор',
    district: 'Красная Поляна',
    lat: 43.6725,
    lng: 40.2975,
    image: 'https://images.unsplash.com/photo-1551524164-687a55dd1126?w=1200&q=80',
    bestSeason: 'Зима — снег; лето — треккинг и виды',
    visitTime: 'Полный день',
    priceHint: 'Канатки и подъёмники — по тарифам курорта',
    sortOrder: 20,
    featuresJson: features([
      { icon: 'mountain', title: 'Канатки', text: 'Подъём на плато с панорамой Кавказа' },
      { icon: 'footprints', title: 'Тропы', text: 'Летние маршруты разной сложности' },
      { icon: 'coffee', title: 'Променад', text: 'Кафе и магазины у реки Мзымта' },
    ]),
    tips: 'Билеты на канатку лучше брать онлайн. На высоте прохладнее — возьмите ветровку.',
  },
  {
    id: 'place_dendrarium',
    slug: 'dendrarium',
    title: 'Дендрарий',
    summary: 'Ботанический сад с субтропиками и видовой башней.',
    description:
      'Сочинский дендрарий — классика города: аллеи, редкие деревья, пруд с лебедями и канатная дорога к верхней площадке. Отсюда открывается вид на море и курортный проспект.',
    category: 'PARK',
    address: 'г. Сочи, Курортный пр., 74',
    district: 'Центр / Хостинский',
    lat: 43.5697,
    lng: 39.7415,
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
    bestSeason: 'Весна–осень; зимой тоже зелено',
    visitTime: '1,5–3 часа',
    priceHint: 'Входной билет; канатка отдельно',
    sortOrder: 30,
    featuresJson: features([
      { icon: 'leaf', title: 'Коллекция растений', text: 'Субтропики со всего мира' },
      { icon: 'cable', title: 'Канатка', text: 'Подъём к видовой площадке' },
      { icon: 'bird', title: 'Пруд', text: 'Лебеди и фото у воды' },
    ]),
    tips: 'Удобная обувь — много подъёмов. Утром меньше людей и мягче свет.',
  },
  {
    id: 'place_agura',
    slug: 'agurskie-vodopady',
    title: 'Агурские водопады',
    summary: 'Лесная тропа к каскадам у Орлиных скал.',
    description:
      'Один из самых популярных природных маршрутов Сочи: тропа вдоль Агуры к нижнему, среднему и верхнему водопадам. Можно продолжить путь к Орлиным скалам и смотровым площадкам.',
    category: 'MOUNTAIN',
    address: 'г. Сочи, ущелье реки Агура',
    district: 'Хоста',
    lat: 43.55,
    lng: 39.825,
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=1200&q=80',
    bestSeason: 'Апрель–октябрь; после дождей водопады полноводнее',
    visitTime: '2–4 часа',
    priceHint: 'Вход на тропу обычно платный',
    sortOrder: 40,
    featuresJson: features([
      { icon: 'droplets', title: 'Каскады', text: 'Три основных водопада на маршруте' },
      { icon: 'trees', title: 'Тень леса', text: 'Спасение в жаркий день' },
      { icon: 'boot', title: 'Треккинг', text: 'Средняя сложность, есть ступени' },
    ]),
    tips: 'Нескользящая обувь обязательна. Возьмите воду — на тропе мало точек продажи.',
  },
  {
    id: 'place_akhun',
    slug: 'orlinye-skaly-akhun',
    title: 'Орлиные скалы / гора Ахун',
    summary: 'Смотровые над Хостой и башня на Ахуне.',
    description:
      'Орлиные скалы — каменные уступы с видами на море и ущелье Агуры. Рядом маршрут к горе Ахун со смотровой башней: панорама от центра Сочи до Адлера в ясную погоду.',
    category: 'VIEWPOINT',
    address: 'г. Сочи, Орлиные скалы / гора Ахун',
    district: 'Хоста',
    lat: 43.5508,
    lng: 39.843,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    bestSeason: 'Ясные дни весна–осень',
    visitTime: '2–3 часа',
    priceHint: 'Вход на площадки / башню — по тарифу',
    sortOrder: 50,
    featuresJson: features([
      { icon: 'eye', title: 'Панорама', text: 'Море, горы и курортная линия' },
      { icon: 'mountain', title: 'Башня Ахун', text: 'Классическая смотровая Сочи' },
      { icon: 'camera', title: 'Рассвет/закат', text: 'Лучшее время для кадров' },
    ]),
    tips: 'Совместите с Агурскими водопадами за один день. На смотровых ветрено.',
  },
  {
    id: 'place_tis_samshit',
    slug: 'tiso-samshitovaya-roshcha',
    title: 'Тисо-самшитовая роща',
    summary: 'Древний лес Кавказского заповедника у Хосты.',
    description:
      'Участок Кавказского биосферного заповедника: тис и самшит, карстовые скалы и тенистые тропы. Короткий и большой круги — на выбор. Важный природный объект Большого Сочи.',
    category: 'PARK',
    address: 'г. Сочи, Хоста, Тисо-самшитовая роща',
    district: 'Хоста',
    lat: 43.543,
    lng: 39.842,
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=80',
    bestSeason: 'Круглый год; летом прохладно в тени',
    visitTime: '1–2,5 часа',
    priceHint: 'Входной билет заповедника',
    sortOrder: 60,
    featuresJson: features([
      { icon: 'shield', title: 'Заповедник', text: 'Охраняемый реликтовый лес' },
      { icon: 'route', title: 'Два круга', text: 'Короткий и большой маршруты' },
      { icon: 'leaf', title: 'Реликты', text: 'Тис и самшит тысячелетней истории' },
    ]),
    tips: 'Не сходите с троп — это заповедник. Комары бывают в тёплый сезон.',
  },
  {
    id: 'place_sochi_park',
    slug: 'sochi-park',
    title: 'Сочи-Парк',
    summary: 'Темапарк у Олимпийского парка для всей семьи.',
    description:
      'Крупный парк аттракционов рядом с Олимпийским парком: американские горки, зоны для малышей, шоу и вечерняя атмосфера. Удобно после прогулки по Медаль-плазе.',
    category: 'FAMILY',
    address: 'г. Сочи, Адлер, ул. Международная, 6',
    district: 'Адлер / Имеретинская',
    lat: 43.405,
    lng: 39.965,
    image: 'https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?w=1200&q=80',
    bestSeason: 'Сезон аттракционов: весна–осень',
    visitTime: 'Полный день',
    priceHint: 'Билеты онлайн выгоднее',
    sortOrder: 70,
    featuresJson: features([
      { icon: 'ferris', title: 'Аттракционы', text: 'Горки и зоны для разного возраста' },
      { icon: 'users', title: 'Семья', text: 'Детские площадки и шоу' },
      { icon: 'ticket', title: 'День-пакет', text: 'Удобно брать билет на весь день' },
    ]),
    tips: 'В выходные очереди длиннее — приходите к открытию. Солнцезащитный крем обязателен.',
  },
  {
    id: 'place_riviera',
    slug: 'plyazh-riviera',
    title: 'Центральный / Ривьера пляж',
    summary: 'Городской пляж у парка «Ривьера» в центре.',
    description:
      'Популярный городской пляж и парк «Ривьера»: галька, шезлонги, кафе и набережная. Удобная точка, если живёте в центре и не хотите ехать в Адлер.',
    category: 'BEACH',
    address: 'г. Сочи, парк Ривьера / пляж Ривьера',
    district: 'Центр',
    lat: 43.5885,
    lng: 39.7165,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
    bestSeason: 'Июнь–сентябрь',
    visitTime: '2–5 часов',
    priceHint: 'Пляж бесплатный; лежаки платные',
    sortOrder: 80,
    featuresJson: features([
      { icon: 'waves', title: 'Море в городе', text: 'Быстрый доступ из центра' },
      { icon: 'trees', title: 'Парк рядом', text: 'Ривьера — прогулки и тень' },
      { icon: 'utensils', title: 'Кафе', text: 'Много точек на набережной' },
    ]),
    tips: 'Утром меньше людей. Возьмите аквашузы — галька.',
  },
  {
    id: 'place_imeretinka',
    slug: 'imeretinskiy-plyazh',
    title: 'Имеретинский пляж',
    summary: 'Широкая береговая линия у Олимпийского парка.',
    description:
      'Пляжная зона Имеретинской низменности: длинный берег, современная инфраструктура и близость к Олимпийскому парку. Хороший выбор для спокойного дня у моря после осмотра арен.',
    category: 'BEACH',
    address: 'г. Сочи, Адлер, Имеретинская низменность',
    district: 'Адлер / Имеретинская',
    lat: 43.4,
    lng: 39.97,
    image: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=1200&q=80',
    bestSeason: 'Июнь–сентябрь',
    visitTime: 'Полдня',
    priceHint: 'Зависит от участка пляжа',
    sortOrder: 90,
    featuresJson: features([
      { icon: 'sun', title: 'Широкий берег', text: 'Места хватает даже в сезон' },
      { icon: 'map', title: 'Рядом Олимппарк', text: 'Можно совместить за день' },
      { icon: 'wind', title: 'Променад', text: 'Прогулки вдоль моря' },
    ]),
    tips: 'Ветер с моря бывает сильнее, чем в центре. Проверьте флаги и спасателей.',
  },
  {
    id: 'place_skypark',
    slug: 'skypark',
    title: 'Скайпарк',
    summary: 'Подвесной мост и адреналин над ущельем Ахцу.',
    description:
      'Sochi Skypark AJ Hackett: подвесной мост, банджи, зиплайн и виды на ущелье. Один из самых «вау»-объектов курорта — даже если просто пройтись по мосту без прыжков.',
    category: 'UNIQUE',
    address: 'г. Сочи, Скайпарк, ущелье Ахцу',
    district: 'Красная Поляна / Ахцу',
    lat: 43.525,
    lng: 39.88,
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&q=80',
    bestSeason: 'Круглый год при хорошей погоде',
    visitTime: '2–4 часа',
    priceHint: 'Вход + аттракции по прайсу',
    sortOrder: 100,
    featuresJson: features([
      { icon: 'bridge', title: 'Мост', text: 'Подвесная конструкция над ущельем' },
      { icon: 'zap', title: 'Адреналин', text: 'Банджи и зиплайн для смелых' },
      { icon: 'camera', title: 'Виды', text: 'Фото с высоты без прыжка' },
    ]),
    tips: 'При сильном ветре аттракции могут закрыть. Бронируйте слоты заранее в сезон.',
  },
  {
    id: 'place_vorontsov',
    slug: 'vorontsovskie-peshchery',
    title: 'Воронцовские пещеры',
    summary: 'Карстовые залы в горах над Хостой.',
    description:
      'Система Воронцовских пещер — экскурсионный маршрут по подземным галереям с натёчными формами. Температура внутри прохладная круглый год. Отличный контраст к пляжному Сочи.',
    category: 'UNIQUE',
    address: 'г. Сочи, Воронцовские пещеры',
    district: 'Хоста / горы',
    lat: 43.615,
    lng: 39.94,
    image: 'https://images.unsplash.com/photo-1504214208698-94b0d02d8e1c?w=1200&q=80',
    bestSeason: 'Круглый год',
    visitTime: '1,5–2,5 часа',
    priceHint: 'Экскурсионный билет',
    sortOrder: 110,
    featuresJson: features([
      { icon: 'cave', title: 'Подземелье', text: 'Карстовые залы и коридоры' },
      { icon: 'thermometer', title: 'Прохлада', text: 'Спасение в жару' },
      { icon: 'guide', title: 'Экскурсия', text: 'Лучше с гидом по маршруту' },
    ]),
    tips: 'Куртка или кофта — внутри ~12°C. Удобная обувь без каблуков.',
  },
  {
    id: 'place_matsesta',
    slug: 'matsesta',
    title: 'Мацеста',
    summary: 'Легендарные сероводородные источники Сочи.',
    description:
      'Мацеста — символ курортного Сочи: бальнеология, характерный запах источников и история советского здравкурорта. Можно совместить с прогулкой по долине и осмотром окрестностей.',
    category: 'HISTORICAL',
    address: 'г. Сочи, Мацеста',
    district: 'Хостинский',
    lat: 43.545,
    lng: 39.795,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80',
    bestSeason: 'Круглый год',
    visitTime: '1–3 часа',
    priceHint: 'Процедуры — по прайсу санаториев',
    sortOrder: 120,
    featuresJson: features([
      { icon: 'droplet', title: 'Источники', text: 'Сероводородные воды курорта' },
      { icon: 'landmark', title: 'История', text: 'Классика сочинской здравницы' },
      { icon: 'heart', title: 'Релакс', text: 'Спокойный день без гонок' },
    ]),
    tips: 'Процедуры — по записи и показаниям. Для прогулки хватит долины и видов.',
  },
  {
    id: 'place_marine_station',
    slug: 'morskoy-vokzal',
    title: 'Морской вокзал',
    summary: 'Визитная открытка центральной набережной.',
    description:
      'Морской вокзал Сочи — архитектурная доминанта набережной: башня со шпилем, скульптуры времён года и прогулочная зона у причалов. Отсюда начинаются морские прогулки и фотосессии.',
    category: 'HISTORICAL',
    address: 'г. Сочи, ул. Войкова, 1',
    district: 'Центр',
    lat: 43.5805,
    lng: 39.7185,
    image: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1200&q=80',
    bestSeason: 'Круглый год; особенно красиво вечером',
    visitTime: '45–90 минут',
    priceHint: 'Территория бесплатна; прогулки на катере — отдельно',
    sortOrder: 130,
    featuresJson: features([
      { icon: 'landmark', title: 'Архитектура', text: 'Шпиль и скульптуры у причала' },
      { icon: 'ship', title: 'Море', text: 'Прогулочные катера' },
      { icon: 'camera', title: 'Открытка', text: 'Одна из главных фототочек города' },
    ]),
    tips: 'Закат и вечерняя подсветка — лучшее время. Рядом набережная и центр.',
  },
  {
    id: 'place_history_museum',
    slug: 'muzey-istorii-sochi',
    title: 'Музей истории Сочи',
    summary: 'Город от черкесских аулов до Олимпиады.',
    description:
      'Музей истории города-курорта: экспозиции о природе, этнографии, курортном строительстве и Олимпиаде-2014. Хорошая точка, если хотите понять Сочи глубже пляжей и канаток.',
    category: 'MUSEUM',
    address: 'г. Сочи, ул. Воронова, 2',
    district: 'Центр',
    lat: 43.585,
    lng: 39.725,
    image: 'https://images.unsplash.com/photo-1566127444979-b3d2b64d626b?w=1200&q=80',
    bestSeason: 'Круглый год; удобно в дождь',
    visitTime: '1–2 часа',
    priceHint: 'Входной билет',
    sortOrder: 140,
    featuresJson: features([
      { icon: 'book', title: 'Экспозиции', text: 'От древности до Игр-2014' },
      { icon: 'cloud-rain', title: 'План Б', text: 'Идеально в непогоду' },
      { icon: 'brain', title: 'Контекст', text: 'Понять город за час-два' },
    ]),
    tips: 'Проверьте часы работы перед визитом. Можно совместить с прогулкой по центру.',
  },
  {
    id: 'place_33_falls',
    slug: '33-vodopada',
    title: '33 водопада',
    summary: 'Каскады в ущелье реки Шахе — классика Лазаревского.',
    description:
      'Природно-этнографический комплекс «33 водопада» в долине Джегош: лесные тропы, купальни у нижних каскадов и колорит Лазаревского района. Один из самых узнаваемых «природных» маршрутов Большого Сочи.',
    category: 'MOUNTAIN',
    address: 'г. Сочи, Лазаревский р-н, аул Большой Кичмай / 33 водопада',
    district: 'Лазаревское',
    lat: 43.825,
    lng: 39.575,
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=1200&q=80',
    bestSeason: 'Май–октябрь; после дождей полноводнее',
    visitTime: '3–5 часов с дорогой',
    priceHint: 'Вход на территорию комплекса',
    sortOrder: 150,
    featuresJson: features([
      { icon: 'droplets', title: 'Каскады', text: 'Серия водопадов в ущелье' },
      { icon: 'trees', title: 'Лес', text: 'Тень и прохлада в жару' },
      { icon: 'car', title: 'День-трип', text: 'Удобно как выезд из центра' },
    ]),
    tips: 'Дорога занимает время — планируйте полный день. Обувь с протектором обязательна.',
  },
  {
    id: 'place_stalin_dacha',
    slug: 'dacha-stalina',
    title: 'Дача Сталина',
    summary: 'Историческая резиденция в зелени над Мацестой.',
    description:
      'Зелёная дача на крутом склоне — музейный объект с атмосферой середины XX века, видами на море и экскурсионными маршрутами. Важная историческая точка для тех, кто собирает «старый Сочи».',
    category: 'HISTORICAL',
    address: 'г. Сочи, Курортный пр. / Зелёная роща (Мацеста)',
    district: 'Хостинский',
    lat: 43.55,
    lng: 39.78,
    image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=80',
    bestSeason: 'Круглый год',
    visitTime: '1–2 часа',
    priceHint: 'Экскурсионный билет',
    sortOrder: 160,
    featuresJson: features([
      { icon: 'landmark', title: 'История', text: 'Резиденция эпохи курортного Сочи' },
      { icon: 'tree', title: 'Роща', text: 'Теневой склон над морем' },
      { icon: 'guide', title: 'Экскурсия', text: 'Лучше с гидом по интерьерам' },
    ]),
    tips: 'Билеты лучше брать заранее в сезон. Совмещается с Мацестой.',
  },
  {
    id: 'place_navaginskaya',
    slug: 'navaginskaya',
    title: 'Навагинская улица',
    summary: 'Пешеходная артерия центра с кафе и фонтанами.',
    description:
      'Главная прогулочная улица центра Сочи: фонтаны, уличные музыканты, магазины и выход к Морскому вокзалу. База для вечернего маршрута «центр → набережная → вокзал».',
    category: 'UNIQUE',
    address: 'г. Сочи, ул. Навагинская',
    district: 'Центр',
    lat: 43.5858,
    lng: 39.7195,
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1200&q=80',
    bestSeason: 'Круглый год; особенно вечер летом',
    visitTime: '1–2 часа',
    priceHint: 'Бесплатно',
    sortOrder: 170,
    featuresJson: features([
      { icon: 'footprints', title: 'Променад', text: 'Пешеходная зона без машин' },
      { icon: 'coffee', title: 'Кафе', text: 'Точки на любой вкус' },
      { icon: 'moon', title: 'Вечер', text: 'Подсветка и живая атмосфера' },
    ]),
    tips: 'В пик сезона людно после 19:00. Удобная точка старта вечернего маршрута.',
  },
  {
    id: 'place_winter_theater',
    slug: 'zimniy-teatr',
    title: 'Зимний театр',
    summary: 'Колоннада и сцена курортного Сочи на Курортном проспекте.',
    description:
      'Зимний театр — архитектурная доминанта Курортного проспекта с колоннадой и регулярной афишей. Рядом парк и выход к морю: удобно для культурного вечера или дневной прогулки по «парадному» Сочи.',
    category: 'HISTORICAL',
    address: 'г. Сочи, Театральная пл., 2',
    district: 'Центр',
    lat: 43.5755,
    lng: 39.7255,
    image: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80',
    bestSeason: 'Круглый год по афише',
    visitTime: 'Спектакль или 30–60 мин снаружи',
    priceHint: 'Территория бесплатна; билеты — по афише',
    sortOrder: 180,
    featuresJson: features([
      { icon: 'landmark', title: 'Архитектура', text: 'Колоннада и площадь' },
      { icon: 'ticket', title: 'Афиша', text: 'Концерты и спектакли' },
      { icon: 'camera', title: 'Фото', text: 'Классический кадр курорта' },
    ]),
    tips: 'Проверьте афишу заранее. Днём красиво для фото, вечером — атмосфера премьеры.',
  },
];

async function main() {
  console.log('Seeding places (Куда сходить в Сочи)…');
  for (const p of PLACES) {
    const data = {
      title: p.title,
      slug: p.slug,
      summary: p.summary,
      description: p.description,
      category: p.category,
      address: p.address,
      district: p.district,
      lat: p.lat,
      lng: p.lng,
      image: p.image,
      featuresJson: p.featuresJson,
      tips: p.tips,
      bestSeason: p.bestSeason,
      visitTime: p.visitTime,
      priceHint: p.priceHint,
      status: 'PUBLISHED',
      sortOrder: p.sortOrder,
      isDemoData: true,
    };
    await prisma.place.upsert({
      where: { id: p.id },
      create: { id: p.id, ...data },
      update: data,
    });
    console.log('  ✓', p.title);
  }
  console.log(`Done: ${PLACES.length} places`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
