#!/usr/bin/env bash
# Create dedicated OS accounts for YoungPortal deploy + HA (idempotent).
#
# Users:
#   yp-deploy — rsync/deploy, docker compose, nginx reload (limited sudo)
#   yp-ha     — replica sync over SSH (docker group + sync binary)
#
# Usage (as root on the VPS):
#   bash scripts/setup-project-users.sh
#   bash scripts/setup-project-users.sh --app-dir /opt/sochi-portal
#   bash scripts/setup-project-users.sh --with-keys   # generate local HA ed25519 if missing
#
# After this, prefer:
#   deploy  → yp-deploy@host (SSH key)
#   HA peer → yp-ha@host (SSH key)  — see scripts/bootstrap-ha-ssh.sh
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/sochi-portal}"
DEPLOY_USER="${DEPLOY_USER:-yp-deploy}"
HA_USER="${HA_USER:-yp-ha}"
WITH_KEYS=0
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --app-dir) APP_DIR="$2"; shift 2 ;;
    --deploy-user) DEPLOY_USER="$2"; shift 2 ;;
    --ha-user) HA_USER="$2"; shift 2 ;;
    --with-keys) WITH_KEYS=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help)
      sed -n '2,20p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

if [[ $(id -u) -ne 0 && $DRY_RUN -eq 0 ]]; then
  echo "Run as root"; exit 1
fi

if [[ $DRY_RUN -eq 1 ]]; then
  echo "[dry-run] would ensure users $DEPLOY_USER + $HA_USER, docker group, sudoers, dirs under $APP_DIR"
  exit 0
fi

command -v useradd >/dev/null
getent group docker >/dev/null 2>&1 || groupadd docker

ensure_user() {
  local u="$1"
  if id "$u" >/dev/null 2>&1; then
    echo "  user $u exists"
  else
    useradd --create-home --shell /bin/bash --groups docker "$u"
    echo "  created $u"
  fi
  usermod -aG docker "$u"
  mkdir -p "/home/$u/.ssh"
  chmod 700 "/home/$u/.ssh"
  touch "/home/$u/.ssh/authorized_keys"
  chmod 600 "/home/$u/.ssh/authorized_keys"
  chown -R "$u:$u" "/home/$u/.ssh"
}

echo "==> Project users for $APP_DIR"
ensure_user "$DEPLOY_USER"
ensure_user "$HA_USER"

# App tree readable by deploy/ha; uploads writable for sync restore
if [[ -d "$APP_DIR" ]]; then
  chgrp -R docker "$APP_DIR" 2>/dev/null || true
  chmod -R g+rX "$APP_DIR" 2>/dev/null || true
  if [[ -d "$APP_DIR/public/uploads" ]]; then
    chown -R "${HA_USER}:docker" "$APP_DIR/public/uploads" || true
    chmod -R ug+rwX "$APP_DIR/public/uploads" || true
  fi
fi

# State / logs for HA
mkdir -p /var/lib/yp-ha /var/log
touch /var/log/yp-ha-sync.log
chown -R "${HA_USER}:docker" /var/lib/yp-ha
chown "${HA_USER}:docker" /var/log/yp-ha-sync.log
chmod 750 /var/lib/yp-ha
chmod 640 /var/log/yp-ha-sync.log

# Install sync binary if present in app tree
if [[ -f "$APP_DIR/scripts/yp-ha-sync.sh" ]]; then
  install -m 755 "$APP_DIR/scripts/yp-ha-sync.sh" /usr/local/sbin/yp-ha-sync
  chown root:docker /usr/local/sbin/yp-ha-sync
  chmod 750 /usr/local/sbin/yp-ha-sync
fi

# Limited sudo for deploy (nginx + compose helpers)
SUDOERS_D=/etc/sudoers.d/yp-portal
cat > "$SUDOERS_D" <<EOF
# YoungPortal project accounts — generated by setup-project-users.sh
Defaults:${DEPLOY_USER} !requiretty
Defaults:${HA_USER} !requiretty
${DEPLOY_USER} ALL=(root) NOPASSWD: /usr/bin/docker, /usr/bin/docker-compose, /usr/local/bin/docker-compose, /bin/systemctl reload nginx, /bin/systemctl reload nginx.service, /usr/sbin/nginx -t, /usr/bin/certbot
${HA_USER} ALL=(root) NOPASSWD: /usr/bin/docker, /usr/bin/docker-compose, /usr/local/bin/docker-compose, /usr/local/sbin/yp-ha-sync
EOF
chmod 440 "$SUDOERS_D"
visudo -cf "$SUDOERS_D"

if [[ $WITH_KEYS -eq 1 ]]; then
  KEY="/home/${HA_USER}/.ssh/id_ed25519"
  if [[ ! -f "$KEY" ]]; then
    sudo -u "$HA_USER" ssh-keygen -t ed25519 -N '' -f "$KEY" -C "yp-ha@$(hostname -f 2>/dev/null || hostname)"
    echo "  generated $KEY"
  else
    echo "  key exists $KEY"
  fi
fi

# Marker for operators / orchestrators
mkdir -p /etc/yp-portal
cat > /etc/yp-portal/accounts.env <<EOF
# Generated $(date -u +%Y-%m-%dT%H:%M:%SZ)
APP_DIR=$APP_DIR
DEPLOY_USER=$DEPLOY_USER
HA_USER=$HA_USER
EOF
chmod 644 /etc/yp-portal/accounts.env

cat <<SUMMARY

══════════════════════════════════════════════════════════════
  Project users ready
══════════════════════════════════════════════════════════════
  Deploy:  $DEPLOY_USER  (docker + limited sudo)
  HA:      $HA_USER      (docker + yp-ha-sync)
  Marker:  /etc/yp-portal/accounts.env

  Next:
    # put your laptop pubkey:
    #   echo 'ssh-ed25519 AAAA…' >> /home/$DEPLOY_USER/.ssh/authorized_keys
    # pair two nodes:
    #   bash scripts/bootstrap-ha-ssh.sh --peer-host … --peer-ssh-port 4488
    #   bash scripts/setup-replica-pair.sh …
══════════════════════════════════════════════════════════════
SUMMARY
